### ISSUE TITLE
Today report errors if there is entry with no name

### ISSUE THREAD

**Issue by beauraines** [beauraines/toggl-cli#11]
I was running an timer that had no name e.g. undefined #2563211804  and then tried to run the today report. It errored with the following message

```
TypeError: Cannot read properties of undefined (reading 'name')
    at /Users/beauraines/projects/toggl-cli-node/cmds/today.js:42:35
    at Array.map (<anonymous>)
    at Object.exports.handler (/Users/beauraines/projects/toggl-cli-node/cmds/today.js:28:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by beauraines** [comment]
Duplicate of #10
